services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: blackline_api_container
    ports:
      - "5001:5000"
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=5000
    restart: unless-stopped

